---
- name: Create shared folder if it doesn't exist
  file:
    path: ./shared
    state: directory
    mode: 0755

- name: Decrypt key pair file
  copy:
    content: "{{deploy_key}}"
    dest: "./shared/deploy.pem"

- name: Set key permissions
  file:
    path: "./shared/deploy.pem"
    mode: 0400

- name: Launch EC2 Instance
  ec2:
     instance_type: "{{service_instance_type}}"
     image: "{{service_ami_id}}"
     wait: true
     exact_count: "{{service_count}}"
     count_tag:
        Name: "{{service_instance_name}}"
     instance_tags:
        Name: "{{service_instance_name}}"
        ServiceType: "{{service_type}}"
        Environment: "{{env}}"
        CommitId: "{{commit_id}}"
     group_id: "{{service_security_group_ids}}"
     vpc_subnet_id: "{{vpc_subnet_id}}"
     assign_public_ip: yes
     monitoring: "{{detailed_monitoring}}"
     region: "{{aws_region}}"
     key_name: "{{aws_key_pair}}"
  register: ec2_info

- name: Tag instances
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ item.id }}"
    tags:
      ServiceType: "{{service_type}}"
      Environment: "{{env}}"
      CommitId: "{{commit_id}}"
  with_items: '{{ec2_info.tagged_instances}}'

- name: Add new instances to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: '{{ec2_info.tagged_instances}}'

- name: Wait for instances to listen on port 22
  wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
  with_items: '{{ec2_info.tagged_instances}}'

- name: Add instance to target group
  elb_target:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{aws_region}}"
    target_group_name: "{{alb_target_group}}"
    target_id: "{{ item.id }}"
    target_port: 8080
    state: present
  with_items: '{{ec2_info.tagged_instances}}'

- name: Add EC2 instances as known hosts
  known_hosts:
    name: "{{ item.public_ip }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
  with_items: "{{ ec2_info.tagged_instances }}"

